### ISSUE TITLE
Design Landing Page

### ISSUE THREAD

**Issue by kevin-ivy** [kevin-ivy/dm-emergency-paper-locator#4]
# Create basic structure and layout for site
* Need to have separate sections for selecting product and viewing results
* Include option to go to the site for the product selected

- Already partially worked on, creating issue to track changes and updates -

**Comment by kevin-ivy** [comment]
For the product display section, would it be worth it to exchange "count" for something like estimated shipping date?

**Comment by CodyDiab** [comment]
Absolutely, especially if that data is more available in the response. We can have quite a few sections to the response <li> without it looking funky. So if there is anything else that seems pertinent, and is easily accessible, it would be now trouble to add it to the rendered page.

**Comment by CodyDiab** [comment]
Absolutely, especially if that data is more available in the response. We can have quite a few sections to the response list item without it looking funky. So if there is anything else that seems pertinent, and is easily accessible, it would be no trouble to add it to the rendered page.
